name: Patrullaje y Mapa Toluca

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  ejecutar-robots:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar librerías
        run: pip install supabase google-genai shapely

      - name: 1️⃣ Ejecutar Extractor de Noticias
        env:
          GEMINI_KEY: ${{ secrets.GEMINI_KEY }}
          URL_SUPABASE: ${{ secrets.URL_SUPABASE }}
          KEY_SUPABASE: ${{ secrets.KEY_SUPABASE }}
        run: python Extractor_noticias.py

      - name: 2️⃣ Ejecutar Dibujante del Mapa
        env:
          URL_SUPABASE: ${{ secrets.URL_SUPABASE }}
          KEY_SUPABASE: ${{ secrets.KEY_SUPABASE }}
        run: python ver_mapa.py

      - name: 3️⃣ Subir a Netlify
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: npx netlify-cli deploy --prod --dir=.
