name: ejecutar-robots

on:
  push:
    branches: ["main"]
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el código
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar librerías
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: 1️⃣ Ejecutar Extractor de Noticias
        run: python Extractor_noticias.py
        env:
          URL_SUPABASE: ${{ secrets.URL_SUPABASE }}
          KEY_SUPABASE: ${{ secrets.KEY_SUPABASE }}
          GEMINI_KEY: ${{ secrets.GEMINI_KEY }}

      - name: 2️⃣ Ejecutar Dibujante del Mapa
        run: python ver_mapa.py

      - name: Configurar Páginas de GitHub
        uses: actions/configure-pages@v4

      - name: Subir artefacto
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'public'

      - name: 3️⃣ Desplegar a GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
